<a href="https://colab.research.google.com/github/Rawan-Abdelahman/Data_Analysis_Assignments/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Import Dataset

---

In [46]:
data = pd.read_csv('/content/Advertising.csv')
data

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

Exploratory Data Analysis (EDA)

---

In [47]:
data.describe()

       Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [49]:
# check null values
data.isnull().sum() # the output is zero meaning there are no missing data

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [50]:
# check for duplicated values
data.duplicated().sum() # no duplicated values are found

np.int64(0)

In [51]:
# Drop the first 'unnamed' column
data.drop('Unnamed: 0', axis=1, inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [52]:
# Display descriptive statistics such as mean, median, minimum, and maximum values for each feature.

for column in data:
  mean_value = data[column].mean()
  median_value = data[column].median()
  min_value = data[column].min()
  max_value = data[column].max()
  print(f"Statistic for {column}")
  print(f" mean =  {mean_value} \n median = {median_value} \n minimum =  {min_value} \n maximum ={max_value} \n ")

Statistic for TV
 mean =  147.0425
 median = 149.75
 minimum =  0.7
 maximum =296.4

Statistic for Radio
 mean =  23.264000000000006
 median = 22.9
 minimum =  0.0
 maximum =49.6

Statistic for Newspaper
 mean =  30.553999999999995
 median = 25.75
 minimum =  0.3
 maximum =114.0

Statistic for Sales
 mean =  14.0225
 median = 12.9
 minimum =  1.6
 maximum =27.0

In [53]:
correlation = data.corr(numeric_only= True).abs()
correlation.style.background_gradient(cmap='coolwarm')

Building The Model

---

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

In [55]:
#Model Development

X = data.drop('Sales', axis=1)
y = data['Sales']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Model Evaluation
print("mean squred error(MSE)", mse)
print("mean absolute error(MAE)", mae)
print("R-Squared", r2)

mean squred error(MSE) 3.1740973539761033
mean absolute error(MAE) 1.4607567168117603
R-Squared 0.899438024100912